spring.datasource.url=jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
server.port=8081

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always